[tool.poetry]
name = "fastapi-llm-app"
version = "0.1.1"
description = "SaaS LLM Web UI with FastAPI and HTMX"
authors = ["pavanepour.k <pavanepour@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11"
fastapi = 0.116.1
uvicorn = 0.35.0
sqlmodel = 0.0.24
sqlalchemy = 2.0.41
aiosqlite = 0.21.0
python-jose = 3.5.0
passlib = 1.7.4
python-multipart = 0.0.20
httpx = 0.28.1
redis = 6.2.0
sentence-transformers = 5.0.0
faiss-cpu = 1.11.0.post1
pymupdf = 1.26.3
pydantic = 2.11.7
pydantic-settings = 2.10.1
python-dotenv = 1.1.1
jinja2 = 3.1.6

[tool.poetry.group.dev.dependencies]
pytest = 8.4.1
pytest-asyncio = 1.1.0
pytest-cov = 6.2.1
black = 25.1.0
ruff = 0.12.4
mypy = 1.17.0
pre-commit = 4.2.0
faker = 37.4.2

[build-system]
requires = 0.11.1
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.ruff]
target-version = "py311"
line-length = 88
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true
